version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - PHLAK

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - PHLAK
