sudo: false

language: php

env:
  - COMPOSER_PREFER=default
  - COMPOSER_PREFER=lowest

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - vendor

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - npm ci

install:
  - "[[ $COMPOSER_PREFER == 'lowest' ]] && composer update --prefer-lowest || composer update"
