version: '3'

services:
  app:
    container_name: chriskankiewicz-dot-com-app
    build:
      context: .
      args:
        INSTALL_XDEBUG: 'true'
    environment:
      APP_ENV: 'docker'
      LOG_CHANNEL: 'stderr'
      DB_HOST: 'chriskankiewicz-dot-com-mysql'
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'chriskankiewicz-dot-com-redis'
      REDIS_PORT: 6379
      VIRTUAL_HOST: chriskankiewicz.local
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.dev.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.dev.conf:/etc/apache2/sites-available/000-default.conf
    restart: unless-stopped

  mysql:
    container_name: chriskankiewicz-dot-com-mysql
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped

  redis:
    container_name: chriskankiewicz-dot-com-redis
    image: redis:5.0
    ports:
      - ${REDIS_PORT}:6379
    restart: unless-stopped

networks:
  default:
    external:
      name: development
