version: '3.4'

services:
  app:
    container_name: chriskankiewicz-dot-com-app
    build:
      context: .
      args:
        NOVA_USERNAME: ${NOVA_USERNAME?Not set or empty}
        NOVA_PASSWORD: ${NOVA_PASSWORD?Not set or empty}
        FONT_AWESOME_TOKEN: ${FONT_AWESOME_TOKEN?Not set or empty}
      target: development
    environment:
      APP_ENV: 'local'
      LOG_CHANNEL: 'stderr'
      DB_HOST: 'chriskankiewicz-dot-com-mysql'
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-app}
      DB_USERNAME: ${DB_USERNAME:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      CACHE_DRIVER: 'redis'
      REDIS_HOST: 'chriskankiewicz-dot-com-redis'
      REDIS_PORT: 6379
      VIRTUAL_HOST: chriskankiewicz.local
    volumes:
      - ./:/var/www/html
      - ./.docker/php/config/php.dev.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache2/config/000-default.dev.conf:/etc/apache2/sites-available/000-default.conf
    restart: on-failure

  mysql:
    container_name: chriskankiewicz-dot-com-mysql
    image: mysql:8.0
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    restart: on-failure

  redis:
    container_name: chriskankiewicz-dot-com-redis
    image: redis:5.0
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: on-failure

networks:
  default:
    external:
      name: development
