#!/bin/bash

# Custom Docker Hub build hook. For reference, see:
# https://docs.docker.com/docker-cloud/builds/advanced/

docker build \
    --build-arg COMPOSER_AUTH=${COMPOSER_AUTH} \
    --build-arg FONT_AWESOME_TOKEN=${FONT_AWESOME_TOKEN} \
    --tag ${IMAGE_NAME} .
