#!/bin/bash

# Custom Docker Hub build hook. For reference, see:
# https://docs.docker.com/docker-cloud/builds/advanced/

docker build \
    --build-arg FONT_AWESOME_TOKEN=${FONT_AWESOME_TOKEN} \
    --build-arg NOVA_USERNAME=${NOVA_USERNAME} \
    --build-arg NOVA_PASSWORD=${NOVA_PASSWORD} \
    --tag ${IMAGE_NAME} .
